### ISSUE TITLE
There was an error in the function 'mapping'

### ISSUE THREAD

**Issue by jacorvar** [phe-bioinformatics/PneumoCaT#11]
Hi, I get the following error message when running PneumoCat with several samples:
```
Settings:
  Output files: "out/SNP_based_serotyping/54_S8_L001_R1_001_tmp/reference.fasta.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  out/SNP_based_serotyping/54_S8_L001_R1_001_tmp/reference.fasta
Building a SMALL index
Reading reference sizes
  Time reading reference sizes: 00:00:00
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
  Time to join reference sequences: 00:00:00
bmax according to bmaxDivN setting: 543
Using parameters --bmax 408 --dcv 1024
  Doing ahead-of-time memory usage test
  Passed!  Constructing with these parameters: --bmax 408 --dcv 1024
Constructing suffix-array element generator
Building DifferenceCoverSample
  Building sPrime
  Building sPrimeOrder
  V-Sorting samples
  V-Sorting samples time: 00:00:00
  Allocating rank array
  Ranking v-sort output
  Ranking v-sort output time: 00:00:00
  Invoking Larsson-Sadakane on ranks
  Invoking Larsson-Sadakane on ranks time: 00:00:00
  Sanity-checking and returning
Building samples
Reserving space for 12 sample suffixes
Generating random suffixes
QSorting 12 sample offsets, eliminating duplicates
QSorting sample offsets, eliminating duplicates time: 00:00:00
Multikey QSorting 12 samples
  (Using difference cover)
  Multikey QSorting samples time: 00:00:00
Calculating bucket sizes
Splitting and merging
  Splitting and merging time: 00:00:00
Avg bucket size: 2175 (target: 407)
Converting suffix-array elements to index image
Allocating ftab, absorbFtab
Entering Ebwt loop
Getting block 1 of 1
  No samples; assembling all-inclusive block
  Sorting block of length 2175 for bucket 1
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 2176 for bucket 1
Exited Ebwt loop
fchr[A]: 0
fchr[C]: 804
fchr[G]: 1068
fchr[T]: 1490
fchr[$]: 2175
Exiting Ebwt::buildToDisk()
Returning from initFromVector
Wrote 4195263 bytes to primary EBWT file: out/SNP_based_serotyping/54_S8_L001_R1_001_tmp/reference.fasta.1.bt2
Wrote 548 bytes to secondary EBWT file: out/SNP_based_serotyping/54_S8_L001_R1_001_tmp/reference.fasta.2.bt2
Re-opening _in1 and _in2 as input streams
Returning from Ebwt constructor
Headers:
    len: 2175
    bwtLen: 2176
    sz: 544
    bwtSz: 544
    lineRate: 6
    offRate: 4
    offMask: 0xfffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 80
    ftabLen: 1048577
    ftabSz: 4194308
    offsLen: 136
    offsSz: 544
    lineSz: 64
    sideSz: 64
    sideBwtSz: 48
    sideBwtLen: 192
    numSides: 12
    numLines: 12
    ebwtTotLen: 768
    ebwtTotSz: 768
    color: 0
    reverse: 0
Total time for call to driver() for forward index: 00:00:00
Reading reference sizes
  Time reading reference sizes: 00:00:00
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
  Time to join reference sequences: 00:00:00
  Time to reverse reference sequence: 00:00:00
bmax according to bmaxDivN setting: 543
Using parameters --bmax 408 --dcv 1024
  Doing ahead-of-time memory usage test
  Passed!  Constructing with these parameters: --bmax 408 --dcv 1024
Constructing suffix-array element generator
Building DifferenceCoverSample
  Building sPrime
  Building sPrimeOrder
  V-Sorting samples
  V-Sorting samples time: 00:00:00
  Allocating rank array
  Ranking v-sort output
  Ranking v-sort output time: 00:00:00
  Invoking Larsson-Sadakane on ranks
  Invoking Larsson-Sadakane on ranks time: 00:00:00
  Sanity-checking and returning
Building samples
Reserving space for 12 sample suffixes
Generating random suffixes
QSorting 12 sample offsets, eliminating duplicates
QSorting sample offsets, eliminating duplicates time: 00:00:00
Multikey QSorting 12 samples
  (Using difference cover)
  Multikey QSorting samples time: 00:00:00
Calculating bucket sizes
Splitting and merging
  Splitting and merging time: 00:00:00
Avg bucket size: 2175 (target: 407)
Converting suffix-array elements to index image
Allocating ftab, absorbFtab
Entering Ebwt loop
Getting block 1 of 1
  No samples; assembling all-inclusive block
  Sorting block of length 2175 for bucket 1
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 2176 for bucket 1
Exited Ebwt loop
fchr[A]: 0
fchr[C]: 804
fchr[G]: 1068
fchr[T]: 1490
fchr[$]: 2175
Exiting Ebwt::buildToDisk()
Returning from initFromVector
Wrote 4195263 bytes to primary EBWT file: out/SNP_based_serotyping/54_S8_L001_R1_001_tmp/reference.fasta.rev.1.bt2
Wrote 548 bytes to secondary EBWT file: out/SNP_based_serotyping/54_S8_L001_R1_001_tmp/reference.fasta.rev.2.bt2
Re-opening _in1 and _in2 as input streams
Returning from Ebwt constructor
Headers:
    len: 2175
    bwtLen: 2176
    sz: 544
    bwtSz: 544
    lineRate: 6
    offRate: 4
    offMask: 0xfffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 80
    ftabLen: 1048577
    ftabSz: 4194308
    offsLen: 136
    offsSz: 544
    lineSz: 64
    sideSz: 64
    sideBwtSz: 48
    sideBwtLen: 192
    numSides: 12
    numLines: 12
    ebwtTotLen: 768
    ebwtTotSz: 768
    color: 0
    reverse: 1
Total time for backward call to driver() for mirror index: 00:00:00
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
stat: No such file or directory
Warning: Could not open read file "data/54_S8_L001_R1_002.fastq.gz" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1
There was an error in the function 'mapping'
____________________________________________________________
Traceback (most recent call last):
  File "/mnt/beegfs/jacorvar/207/PneumoCaT-master/modules/utility_functions.py", line 59, in try_and_except
    return function(*parameters, **named_parameters)
  File "/mnt/beegfs/jacorvar/207/PneumoCaT-master/modules/bowtie_map.py", line 99, in mapping
    sam_mod = modify_bowtie_sam(samfile, logger)
  File "/mnt/beegfs/jacorvar/207/PneumoCaT-master/modules/bowtie_map.py", line 56, in modify_bowtie_sam
    with open(samfile) as sam, open(samfile + '.mod', 'w') as sam_mod:
IOError: [Errno 2] No such file or directory: 'out/SNP_based_serotyping/54_S8_L001_R1_001_tmp/54_S8_L001_R1_001.sam'
```
How should I interpret it?
I'm using Bowtie2 and Samtools versions installed on the system.

**Comment by jacorvar** [comment]
Hi Natalie,

sure, the command is the following:

```
python PneumoCaT-master/PneumoCaT.py -o out -1 data/35_S22_L001_R1_001.fastq.gz -2 data/35_S22_L001_R2_001.fastq.gz -b $(which bowtie2) -t 16
```

plus the output for such command:
```
running bowtie index
['22F']
Settings:
  Output files: "out/SNP_based_serotyping/35_S22_L001_R1_001_tmp/reference.fasta.*.bt2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Max bucket size: default
  Max bucket size, sqrt multiplier: default
  Max bucket size, len divisor: 4
  Difference-cover sample period: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  out/SNP_based_serotyping/35_S22_L001_R1_001_tmp/reference.fasta
Building a SMALL index
Reading reference sizes
  Time reading reference sizes: 00:00:00
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
  Time to join reference sequences: 00:00:00
bmax according to bmaxDivN setting: 449
Using parameters --bmax 337 --dcv 1024
  Doing ahead-of-time memory usage test
  Passed!  Constructing with these parameters: --bmax 337 --dcv 1024
Constructing suffix-array element generator
Building DifferenceCoverSample
  Building sPrime
  Building sPrimeOrder
  V-Sorting samples
  V-Sorting samples time: 00:00:00
  Allocating rank array
  Ranking v-sort output
  Ranking v-sort output time: 00:00:00
  Invoking Larsson-Sadakane on ranks
  Invoking Larsson-Sadakane on ranks time: 00:00:00
  Sanity-checking and returning
Building samples
Reserving space for 12 sample suffixes
Generating random suffixes
QSorting 12 sample offsets, eliminating duplicates
QSorting sample offsets, eliminating duplicates time: 00:00:00
Multikey QSorting 12 samples
  (Using difference cover)
  Multikey QSorting samples time: 00:00:00
Calculating bucket sizes
Splitting and merging
  Splitting and merging time: 00:00:00
Avg bucket size: 1797 (target: 336)
Converting suffix-array elements to index image
Allocating ftab, absorbFtab
Entering Ebwt loop
Getting block 1 of 1
  No samples; assembling all-inclusive block
  Sorting block of length 1797 for bucket 1
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 1798 for bucket 1
Exited Ebwt loop
fchr[A]: 0
fchr[C]: 567
fchr[G]: 853
fchr[T]: 1236
fchr[$]: 1797
Exiting Ebwt::buildToDisk()
Returning from initFromVector
Wrote 4195131 bytes to primary EBWT file: out/SNP_based_serotyping/35_S22_L001_R1_001_tmp/reference.fasta.1.bt2
Wrote 456 bytes to secondary EBWT file: out/SNP_based_serotyping/35_S22_L001_R1_001_tmp/reference.fasta.2.bt2
Re-opening _in1 and _in2 as input streams
Returning from Ebwt constructor
Headers:
    len: 1797
    bwtLen: 1798
    sz: 450
    bwtSz: 450
    lineRate: 6
    offRate: 4
    offMask: 0xfffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 80
    ftabLen: 1048577
    ftabSz: 4194308
    offsLen: 113
    offsSz: 452
    lineSz: 64
    sideSz: 64
    sideBwtSz: 48
    sideBwtLen: 192
    numSides: 10
    numLines: 10
    ebwtTotLen: 640
    ebwtTotSz: 640
    color: 0
    reverse: 0
Total time for call to driver() for forward index: 00:00:00
Reading reference sizes
  Time reading reference sizes: 00:00:00
Calculating joined length
Writing header
Reserving space for joined string
Joining reference sequences
  Time to join reference sequences: 00:00:00
  Time to reverse reference sequence: 00:00:00
bmax according to bmaxDivN setting: 449
Using parameters --bmax 337 --dcv 1024
  Doing ahead-of-time memory usage test
  Passed!  Constructing with these parameters: --bmax 337 --dcv 1024
Constructing suffix-array element generator
Building DifferenceCoverSample
  Building sPrime
  Building sPrimeOrder
  V-Sorting samples
  V-Sorting samples time: 00:00:00
  Allocating rank array
  Ranking v-sort output
  Ranking v-sort output time: 00:00:00
  Invoking Larsson-Sadakane on ranks
  Invoking Larsson-Sadakane on ranks time: 00:00:00
  Sanity-checking and returning
Building samples
Reserving space for 12 sample suffixes
Generating random suffixes
QSorting 12 sample offsets, eliminating duplicates
QSorting sample offsets, eliminating duplicates time: 00:00:00
Multikey QSorting 12 samples
  (Using difference cover)
  Multikey QSorting samples time: 00:00:00
Calculating bucket sizes
Splitting and merging
  Splitting and merging time: 00:00:00
Avg bucket size: 1797 (target: 336)
Converting suffix-array elements to index image
Allocating ftab, absorbFtab
Entering Ebwt loop
Getting block 1 of 1
  No samples; assembling all-inclusive block
  Sorting block of length 1797 for bucket 1
  (Using difference cover)
  Sorting block time: 00:00:00
Returning block of 1798 for bucket 1
Exited Ebwt loop
fchr[A]: 0
fchr[C]: 567
fchr[G]: 853
fchr[T]: 1236
fchr[$]: 1797
Exiting Ebwt::buildToDisk()
Returning from initFromVector
Wrote 4195131 bytes to primary EBWT file: out/SNP_based_serotyping/35_S22_L001_R1_001_tmp/reference.fasta.rev.1.bt2
Wrote 456 bytes to secondary EBWT file: out/SNP_based_serotyping/35_S22_L001_R1_001_tmp/reference.fasta.rev.2.bt2
Re-opening _in1 and _in2 as input streams
Returning from Ebwt constructor
Headers:
    len: 1797
    bwtLen: 1798
    sz: 450
    bwtSz: 450
    lineRate: 6
    offRate: 4
    offMask: 0xfffffff0
    ftabChars: 10
    eftabLen: 20
    eftabSz: 80
    ftabLen: 1048577
    ftabSz: 4194308
    offsLen: 113
    offsSz: 452
    lineSz: 64
    sideSz: 64
    sideBwtSz: 48
    sideBwtLen: 192
    numSides: 10
    numLines: 10
    ebwtTotLen: 640
    ebwtTotSz: 640
    color: 0
    reverse: 1
Total time for backward call to driver() for mirror index: 00:00:00
Warning: gzbuffer added in zlib v1.2.3.5. Unable to change buffer size from default of 8192.
stat: No such file or directory
Warning: Could not open read file "data/35_S22_L001_R1_002.fastq.gz" for reading; skipping...
Error: No input read files were valid
(ERR): bowtie2-align exited with value 1
There was an error in the function 'mapping'
____________________________________________________________
Traceback (most recent call last):
  File "/mnt/beegfs/jacorvar/207/PneumoCaT-master/modules/utility_functions.py", line 59, in try_and_except
    return function(*parameters, **named_parameters)
  File "/mnt/beegfs/jacorvar/207/PneumoCaT-master/modules/bowtie_map.py", line 99, in mapping
    sam_mod = modify_bowtie_sam(samfile, logger)
  File "/mnt/beegfs/jacorvar/207/PneumoCaT-master/modules/bowtie_map.py", line 56, in modify_bowtie_sam
    with open(samfile) as sam, open(samfile + '.mod', 'w') as sam_mod:
IOError: [Errno 2] No such file or directory: 'out/SNP_based_serotyping/35_S22_L001_R1_001_tmp/35_S22_L001_R1_001.sam'
____________________________________________________________
```

It works for about half of the samples.

**Comment by grovesn** [comment]
Hi,

From the error in your output I wonder if it is a similar issue to what is discussed here: [https://github.com/BenLangmead/bowtie2/issues/132](url) 
Can you tell us which version of Bowtie2 you are using?

Thanks,
Natalie

**Comment by jacorvar** [comment]
I have the same version (Bowtie 2.3.2) as the issue you point out. However, it is said that bowtie continues running despite the warnings (https://github.com/BenLangmead/bowtie2/issues/132#issuecomment-338850529).

**Comment by grovesn** [comment]
Hi,

We have found the issue!
The filenames required by PneumoCAT are a specific format and this is why your samples that require SNP level investigations are not working. 
Please make sure that your filenames end with the read number.
E.g your files in the example: data/35_S22_L001_**R1**_001.fastq.gz
need to be changed to data/35_S22_L001_**R1**.fastq.gz

Apologies that I did not notice this sooner. We will change this in the next version of PneumoCAT.
Please let me know if you have any other issues.

Thanks,
Natalie

**Comment by jacorvar** [comment]
Hi Natalie,

I renamed the files and did work as you said. However, I get this time a different error for a couple of samples:

```
running bowtie index
There was an error in the function 'output_all'
____________________________________________________________
Traceback (most recent call last):
  File "/mnt/beegfs/jacorvar/207/PneumoCaT-master/modules/utility_functions.py", line 59, in try_and_except
    return function(*parameters, **named_parameters)
  File "/mnt/beegfs/jacorvar/207/PneumoCaT-master/modules/Serotype_determiner_functions.py", line 306, in output_all
    for pileupcolumn in bamfile.pileup(selected_id):
  File "pysam/libcalignmentfile.pyx", line 1313, in pysam.libcalignmentfile.AlignmentFile.pileup
  File "pysam/libchtslib.pyx", line 675, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig ``
```

**Comment by grovesn** [comment]
Glad you have got it working. Did you have this issue when you were running it with the original filenames? This error occurs earlier in the script than the problem you were having before so I would have expected it to be an issue previously too.

Please can you send your command and let me know if any output files are produced (e.g. the coverage_summary.txt file etc.)

Thanks,
Natalie

**Comment by grovesn** [comment]
This issue is caused by zero mapping to the reference sequences.
Sorry the script does not catch this error and give a more sensible output - we will fix this in the next version!
Basically what is happening is it tries to read the pileup for the operon sequence that had the highest mapping hit (>90%) but none of the serotypes have any coverage in your sample so it cannot retrieve the contig in the pileup step.

The problem is with your fastq files - have you done any QC on them before you ran PneumoCAT (e.g. to make sure you have a reasonable amount of sequencing data) and are you sure that these isolates are S. pneumoniae ?

Natalie

**Comment by jacorvar** [comment]
Hi Natalie,

you're right. Samples giving that error have a very small amount of reads mapping to the genome.
